[build]
  publish = "public"
  command = "npm run build && zola build"

[build.environment]
  ZOLA_VERSION = "0.19.2"

[context.production.environment]
  ZOLA_ENV = "production"

[context.deploy-preview]
  command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "zola build --base-url $DEPLOY_PRIME_URL"